name: Releases

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release (e.g., 1.0.0)"
        required: true
        type: string

env:
  PLUGIN_NAME: obsidian-vale-redux
  TAG: "${{ github.event_name == 'workflow_dispatch' && inputs.tag || github.ref_name }}"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        name: Checkout code
        with:
          fetch-depth: 0 # Fetch all history for changelog

      - uses: actions/setup-node@v6
        name: Setup Node.js
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Build Plugin
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp -r main.js manifest.json styles.css CHANGELOG.md ${{ env.PLUGIN_NAME }}
      - name: Create release notes
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: .github/cliff.toml
          args: -l
        env:
          GIT_CLIFF_TAG: "${{ env.TAG }}"

      - uses: softprops/action-gh-release@v2
        name: Create Release
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          files: |
            ${{ env.PLUGIN_NAME }}/main.js
            ${{ env.PLUGIN_NAME }}/manifest.json
            ${{ env.PLUGIN_NAME }}/styles.css
          tag_name: ${{ env.TAG }}
